POST https://logistics.arcgis.com/arcgis/rest/services/World/ClosestFacility/GPServer/FindClosestFacilities/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=<ACCESS_TOKEN>
&f=json
&incidents={
    "features":[
        {"geometry":{
            "x":-122.449614,
            "y":37.746712
            },
         "attributes":{
            "Name":"Fire Incident"
            }
        }
       ]
    }
&facilities={
    "features":[
        {"geometry":{
            "x":-122.455962,
            "y":37.751316
            },
          "attributes":{
            "Name":"Station 20"
            }
        },
        {"geometry":{
            "x":-122.440825,
            "y":37.753199
            },
          "attributes":{
            "Name":"Station 24"
            }
        },
        {"geometry":{
            "x":-122.457844,
            "y":37.740713
            },
         "attributes":{
            "Name":"Station 39"
            }
        }
    ]
}
&travel_direction=Facility to Incident
&number_of_facilities_to_find=2
&cutoff=3
&time_of_day=1365637673000
&time_of_day_usage=Start Time
&populate_directions=true


