POST https://logistics.arcgis.com/arcgis/rest/services/World/LocationAllocation/GPServer/SolveLocationAllocation/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

f=json
&token=<ACCESS_TOKEN>
&facilities={
    "features": [
        {
            "attributes": {
                "OBJECTID": 1,
                "Name": "Facility A",
                "FacilityType": 0,
                "CurbApproach": 0
            },
            "geometry": {
                "x": -58.557329417999938,
                "y": -34.587693706999971
            }
        },
        {
            "attributes": {
                "OBJECTID": 2,
                "Name": "Facility B",
                "FacilityType": 0,
                "CurbApproach": 0
            },
            "geometry": {
                "x": -58.460247408999976,
                "y": -34.683348039999942
            }
        }
    ]
}
&demand_points={
    "features": [
        {
            "attributes": {
                "OBJECTID": 1,
                "Name": "Household 4",
                "GroupName": "A",
                "Weight": 2,
                "CurbApproach": 0
            },
            "geometry": {
                "x": -58.664405163999959,
                "y": -34.614819562999969
            }
        },
        {
            "attributes": {
                "OBJECTID": 2,
                "Name": "Household 3",
                "GroupName": "A",
                "Weight": 2,
                "CurbApproach": 0
            },
            "geometry": {
                "x": -58.514499119999982,
                "y": -34.496322404999944
            }
        },
        {
            "attributes": {
                "OBJECTID": 3,
                "Name": "Household 2",
                "GroupName": null,
                "Weight": 3,
                "CurbApproach": 0
            },
            "geometry": {
                "x": -58.54162497599998,
                "y": -34.788996107999935
            }
        },
        {
            "attributes": {
                "OBJECTID": 4,
                "Name": "Household 1",
                "GroupName": null,
                "Weight": 5,
                "CurbApproach": 1
            },
            "geometry": {
                "x": -58.40599569799997,
                "y": -34.637662387999967
            }
        }
    ]
}