POST https://logistics.arcgis.com/arcgis/rest/services/World/OriginDestinationCostMatrix/GPServer/GenerateOriginDestinationCostMatrix/jobs/<jobID>/results/output_origins? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

f=pjson
&token=<ACCESS_TOKEN>