POST https://logistics.arcgis.com/arcgis/rest/services/World/OriginDestinationCostMatrix/GPServer/GenerateOriginDestinationCostMatrix/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=<ACCESS_TOKEN>
&f=json
&origins={
    "features": [
      {
        "geometry": {
          "y": 51.5254,
          "x": -0.1891
        },
        "attributes": {
          "Name": "Origin 1",
          "TargetDestinationCount": 2,
          "Cutoff": 120,
          "CurbApproach": 0
        }
      },
      {
        "geometry": {
          "y": 51.5353,
          "x": -0.1744
        },
        "attributes": {
          "Name": "Origin 2",
          "TargetDestinationCount": 3,
          "Cutoff": 90,
          "CurbApproach": 0
        }
      }
    ]
},
&destinations= {
    "features": [
      {
        "geometry": {
          "y": 51.5354,
          "x": -0.1991
        },
        "attributes": {
          "Name": "Destination 1",
          "CurbApproach": 0
        }
      },
      {
        "geometry": {
          "y": 51.5458,
          "x": -0.1844
        },
        "attributes": {
          "Name": "Destination 2",
          "CurbApproach": 0
        }
      }
    ]
}
  
