POST https://logistics.arcgis.com/arcgis/rest/services/World/Route/GPServer/FindRoutes/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

f=json
&token=<ACCESS_TOKEN>
&stops={
    "features":[
        {"attributes":{"Name":"Stop1"
        },
        "geometry":{
            "x":145.0657306480001,
            "y":-37.86513493399997
            }
        },
        {"attributes":{"Name":"Stop2"
        },"
        geometry":{
            "x":145.1049567670001,
            "y":-37.81866925199995
            }
        }
    ]
}