POST https://logistics.arcgis.com/arcgis/rest/services/World/Route/GPServer/FindRoutes/jobs/<yourJobID>? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

f=json
&token=<ACCESS_TOKEN>
&returnMessages=true