POST https://logistics.arcgis.com/arcgis/rest/services/World/Route/GPServer/GenerateServiceAreas/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

f=json
&token=<ACCESS_TOKEN>
&facilities={
    "features":[
        {
            "geometry":{
                "x":-122.253,
                "y":37.757
            },
            "attributes":{
                "Name":"Store5689"
            }
        }
    ]
}
&env:outSr=102100