POST https://logistics.arcgis.com/arcgis/rest/services/World/VehicleRoutingProblem/GPServer/SolveVehicleRoutingProblem/jobs/<yourJobID>? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

returnMessages=true
&f=json
&token=<ACCESS_TOKEN>