POST https://route-api.arcgis.com/arcgis/rest/services/World/ClosestFacility/NAServer/ClosestFacility_World/solveClosestFacility/submitJob? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=<ACCESS_TOKEN>
&f=json
&incidents=-122.4496,37.7467
&facilities={
    "features":
    [
    {"attributes":{
        "Name":"Station 11"
        },
        "geometry":{
        "x":-122.4267,
        "y":37.7486
        }
    },
    {"attributes":{
        "Name":"Station 20"
        },
        "geometry":{
            "x":-122.4561,
            "y":37.7513
            }
    },
    {"attributes":{
        "Name":"Station 24"
        },
        "geometry":{
            "x":-122.4409,
            "y":37.7533
            }
    },
    {"attributes":{
        "Name":"Station 39"
        },
        "geometry":{
            "x":-122.4578,
            "y":37.7407
            }
        }
    ]
}
&defaultTargetFacilityCount=2
&travelDirection=esriNATravelDirectionFromFacility
&defaultCutoff=3
&returnCFRoutes=true
&returnDirections=true
&directionsLengthUnits=esriNAUMiles
&outSR=102100