POST https://route-api.arcgis.com/arcgis/rest/services/World/ClosestFacility/NAServer/OriginDestinationCostMatrix_World/solveODCostMatrix? HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=<ACCESS_TOKEN>
&f=json
&origins={
    "spatialReference":{
        "wkid":102100},
    "features":[
        {"geometry":{
            "x":-13042381.897669187,
            "y":3857625.761983883
            },
            "attributes":{
                "ObjectID":1,"Name":"San Diego"
            }
        },
        {"geometry":{
            "x":-13163008.811087687,
            "y":4035986.6896486743
            },
            "attributes":{
                "ObjectID":2,"Name":"Los Angeles"
            }
        }
    ]
}
&destinations={
    "spatialReference":{
        "wkid":102100},
    "features":[
        {"geometry":{
            "x":-13042381.897669187,
            "y":3857625.761983883
            },
            "attributes":{
                "ObjectID":1,"Name":"San Diego"
            }
        },
        {"geometry":{
            "x":-13163008.811087687,
            "y":4035986.6896486743
            },
            "attributes":{
                "ObjectID":2,"Name":"Los Angeles"
            }
        }
    ]
}