@@Start(SUBMIT_JOB)
POST https://geocode-beta.arcgis.com/arcgis/rest/services/World/GeocodeServer/batchGeocode/beta/submitJob HTTP/1.1
content-type: application/x-www-form-urlencoded
User-Agent: {USER_AGENT}

item = {'itemID': '{ITEM_ID}'}
&token={ACCESS_TOKEN}
&fieldMapping=Address:street_address,City:municipality,Region:state,Postal:zip_code
&outFields='*'
@@End(SUBMIT_JOB)@@Start(CHECK_STATUS)
POST https://geocode-beta.arcgis.com/arcgis/rest/services/World/GeocodeServer/batchGeocode/beta/jobs/{JOB_ID} HTTP/1.1
content-type: application/x-www-form-urlencoded
User-Agent: {USER AGENT}

&token={ACCESS_TOKEN}
@@End(CHECK_STATUS)@@Start(GET_RESULTS)
POST https://geocode-beta.arcgis.com/arcgis/rest/services/World/GeocodeServer/batchGeocode/beta/jobs/{JOB_ID}/results/geocodeResult HTTP/1.1
content-type: application/x-www-form-urlencoded
User-Agent: {USER AGENT}

token: {ACCESS TOKEN}
@@End(GET_RESULTS)