curl --location 'https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/Geoenrichment/enrich' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'f=pjson' \
--data-urlencode 'token=<ACCESS_TOKEN> \
--data-urlencode 'studyAreas=[{'\''geometry'\'':{'\''x'\'': -117.1956, '\''y'\'': 34.0572}}]'